name: dynamoDB-automate

on:
  pull_request:
    branches:
      - automate-dynamoDB

jobs:
  write_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test text
        run: |
          echo "Text sent successfully"
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install nx
        run: npm install
      - run: npx nx test learn-test

  pulumi-up:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}  # Only run if tests passed
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: cd apps/logger-service/provisioning
      - run: pulumi up -y