name: pulumi-up-on-merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  pulumi-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Pulumi
        uses: pulumi/actions/cli@v2
        with:
          args: login

      - name: Select Pulumi stack
        uses: pulumi/actions/cli@v2
        with:
          args: stack select dev-logger-service

      - name: Update resources
        uses: pulumi/actions/cli@v2
        with:
          args: up --yes
