name: Create Test File

on:
  push:
    branches:
      - main

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Test File
        run: |
          echo "This is a test file" > test.txt
          echo "File created successfully"

      - name: Commit and push
        run: |
          git add test.txt
          git commit -m "Add test file"
          git push