name: Create Test File

on:
  push:
    branches:
      - dev

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: npx nx test learn-test --file=apps/learn-test/src/main.spec.ts
