name: Create Test File

on:
  push:
    branches:
      - dev

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Test File
        run: |
          echo "File created successfully"
