name: test-if-test


on:
  push:
    branches:
      - dev
  status: 
    - 'completed'

jobs:
  write_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test text
        run: |
          echo "Text sent successfully"
      - name: test file
        run: |
          cat ett-eller-annet.js
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install nx
        run: npm install nx@18.3.4
      - run: npx nx build learn-test
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install nx
        run: npm install nx@18.3.4
      - run: npx nx test learn-test
  if_error_or_failure:
    runs-on: ubuntu-latest
    if: >-
      github.event.state == 'error' ||
      github.event.state == 'failure'
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo The status is error or failed: $DESCRIPTION

